---
name: HTML-Timeline
version: 1.04
author:
  - 'Ron Savage <ron@savage.net.au>'
abstract: Convert a Gedcom file into a Timeline file
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Carp: 0
  Config::IniFiles: 0
  Gedcom: 0
  Gedcom::Date: 0
  HTML::Template: 0
  Path::Class: 0
  accessors: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  HTML::Timeline:
    file: lib/HTML/Timeline.pm
    version: 1.04
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
